name: Release

on:
  release:
    types: [published]

jobs:

  pre-build:
    name: Update version in source code
    runs-on: windows-latest
    env:
        NEW_VERSION: '${{ github.ref_name }}' 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.release.target_commitish }}

      - name: Update VSIX Version in manifest file
        run: .\scripts\UpdateVsixVersion.ps1
        shell: pwsh

      - name: Run audit scan 
        run: jf audit
        
      - name: Commit and push changes
        run: |
            git config --local user.name "${{ github.actor }}"
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m "Updated VSIX version to ${{ env.NEW_VERSION }}"
            git push

  call-build-workflow:
    # build and package the vsix project
      uses: ./.github/workflows/build-vsix.yml
      with: 
         ref: ${{ github.event.release.target_commitish }}
      needs: pre-build
  
  release:
    runs-on: windows-latest
    needs: call-build-workflow
    steps:
      # download build workflow artifacts
      - name: Download VSIX artifacts
        uses: actions/download-artifact@v3
        with:
            name: vsix-artifacts
            path: ./JFrogVSExtension/bin/Release

      - name: Upload VSIX and attach it to the Release page
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JFrogVSExtension/bin/Release/JFrogVSExtension.vsix
          asset_name: JFrogVSExtension.vsix
          asset_content_type: application/octet-stream

      # upload the vsix file to Visual Studio Marketplace using vsce tool
      - name: Install vsce (Visual Studio Marketplace CLI)
        run: npm install -g vsce

      - name: Publish to Visual Studio Marketplace
        run: vsce publish --pat ${{ secrets.VSCE_PAT }}
        env:
          VSIX_FILE_PATH: ./JFrogVSExtension/bin/Release/JFrogVSExtension.vsix
          VSCE_PAT: ${{ secrets.VSCE_PAT }}