name: Release

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: windows-latest
    needs: call-build-workflow
    steps:

      # build and package the vsix project
      - name: Build VSIX Project
        uses: ./.github/actions/build-vsix
        with: 
           ref: master
           vs-version: latest

      # download build workflow artifacts
      - name: Download VSIX artifacts
        uses: actions/download-artifact@v3
        with:
        # use the unique artifact name from the build action
            name: vsix-artifacts-latest-${{ github.run_id }}
            path: ./JFrogVSExtension/bin/Release

      - name: Upload VSIX and attach it to the Release page
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JFrogVSExtension/bin/Release/JFrogVSExtension.vsix
          asset_name: JFrogVSExtension.vsix
          asset_content_type: application/octet-stream

      # upload the vsix and manifest files to Visual Studio Marketplace using VsixPublisher
      - name: Publish to Visual Studio Marketplace
         # vsix publisher executable is already installed in the github windows runner at the following path
        run: |
          $VSIX_PUBLISHER_PATH = "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VSSDK/VisualStudioIntegration/Tools/Bin/VsixPublisher.exe"
          $VSIX_PATH = "./JFrogVSExtension/bin/Release/JFrogVSExtension.vsix"
          $PUBLISH_MANIFEST_PATH = "./JFrogVSExtension/PublishManifest.json"
          & $VSIX_PUBLISHER_PATH publish -payload $VSIX_PATH -publishManifest $PUBLISH_MANIFEST_PATH -personalAccessToken ${{ secrets.VS_MARKETPLACE_PAT }}
        shell: pwsh
