name: Build and Run Tests

on:
  push:
  pull_request:
    types: [ labeled ]

jobs:
  # call-build-workflow: TODO: delete if works
  #     uses: ./.github/workflows/build-vsix.yml
  #     strategy: 
  #       matrix: 
  #       verify compatibility with the desired Visual Studio versions
  #           vs-version: [17.10, 17.11, 17.12, latest]
  #     with:
  #       ref: ${{ github.event.pull_request.head.sha }}
  #       vs-version: ${{ matrix.vs-version }}

  test:
    runs-on: windows-latest
    # needs: call-build-workflow TODO: remove if works
    strategy: 
        matrix: 
            # verify compatibility with the desired Visual Studio versions
            vs-version: [17.10, 17.11, 17.12, latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Call Build Workflow
      uses: ./.github/workflows/build-vsix.yml
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        vs-version: ${{ matrix.vs-version }}

    # download build workflow artifacts
    - name: Download VSIX artifact
      uses: actions/download-artifact@v3
      with:
        name: vsix-artifacts
        path: ./JFrogVSExtension/bin/Release

    - name: Download Unit Test artifacts
      uses: actions/download-artifact@v3
      with:
        name: tests-artifacts
        path: ./UnitTestJfrogVSExtension/bin/Release

    # run tests in release mode with logs presentation
    - name: Run MSTest Project 
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed" ./UnitTestJfrogVSExtension/bin/Release/UnitTestJfrogVSExtension.dll
