name: Build and Run Tests

on:
  push:
  pull_request:
    type: [ labeled ]

jobs:
  call-build-workflow:
      uses: ./.github/workflows/build-vsix.yml

  test:
    runs-on: windows-latest
    needs: call-build-workflow
    
    steps:
    - name: Download VSIX artifact
      uses: actions/download-artifact@v3
      with:
        name: vsix-artifacts
        path: ./JFrogVSExtension/bin/Release

    - name: Download Unit Test DLL artifact
      uses: actions/download-artifact@v3
      with:
        name: tests-artifacts
        path: ./UnitTestJfrogVSExtension/bin/Release

    - name: Run MSTest Project # run tests in release mode with logs presentation
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed" ./UnitTestJfrogVSExtension/bin/Release/UnitTestJfrogVSExtension.dll
