name: Build and Run Tests

on:
  push:
  pull_request:
    type: [ labeled ]

jobs:
  call-build-workflow:
      uses: ./.github/workflows/build-vsix.yml
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      strategy: 
        matrix: 
        # verify compatibility with the desired Visual Studio versions
            vs-version: [17.10, 17.11, 17.12, latest]

  test:
    runs-on: windows-latest
    needs: call-build-workflow
    strategy: 
        matrix: 
            vs-version: ${{ fromJson(needs.call-build-workflow.outputs['matrix'])}}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        ref: ${{ github.event.pull_request.head.sha }}

    # download build workflow artifacts
    - name: Download VSIX artifact
      uses: actions/download-artifact@v3
      with:
        name: vsix-artifacts
        path: ./JFrogVSExtension/bin/Release

    - name: Download Unit Test artifacts
      uses: actions/download-artifact@v3
      with:
        name: tests-artifacts
        path: ./UnitTestJfrogVSExtension/bin/Release

    # run tests in release mode with logs presentation
    - name: Run MSTest Project 
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed" ./UnitTestJfrogVSExtension/bin/Release/UnitTestJfrogVSExtension.dll
