name: Build and Run Tests

on:
  push:
  pull_request:
    type: [ labeled ]

jobs:
  call-build-workflow:
      uses: ./.github/workflows/build-vsix.yml
      with:
        configuration: 'Release'

  test:
    runs-on: windows-latest
    needs: call-build-workflow
    
    steps:
    - name: Run MSTest Project # run tests in release mode with logs presentation
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed" ./UnitTestJfrogVSExtension/bin/Release/UnitTestJfrogVSExtension.dll

    - name: Save Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
            JFrogVSExtension/bin/Release/
            JFrogVSExtension/bin/Release/*.vsix