name: Build and Run Tests

on:
  push:
  pull_request:
    type: [ labeled ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Call Build VSIX Workflow
      uses: ./.github/workflows/build-vsix.yml

    - name: Run MSTest Project # run tests in release mode with logs presentation
      run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed" ./UnitTestJfrogVSExtension/bin/Release/UnitTestJfrogVSExtension.dll

    - name: Save Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
            JFrogVSExtension/bin/Release/
            JFrogVSExtension/bin/Release/*.vsix